language: generic 
sudo: required
services: 
  - docker


before_install:
  - docker build -t rodneygen22/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true rodneygen22/docker-react npm run test